[build]
  command = "npm run build"  # O comando usado para criar seu projeto
  functions = "api/"       # O diretório das funções Netlify (suas rotas API)
  publish = "public/"      # O diretório onde seu projeto está "publicado"
