[build]
  command = "npm start"
  publish = "." # Substitua "public" pelo diretório de saída da sua API, se aplicável


[[redirects]]
  from = "/*" # Redirecionar todas as solicitações
  to = "/index.js" # Redirecionar para o arquivo principal do aplicativo Node.js
  status = 200 # Use o status 200 para evitar erros "não encontrado"


